services:
  - type: web
    name: mock-test-backend
    env: node
    plan: free
    region: ohio
    buildCommand: npm run install-server && npm run build-server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        sync: false
      - key: REFRESH_SECRET
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
